### ISSUE TITLE
Database tables are missing the UNIQUE constraint

### ISSUE THREAD

**Issue by michael-e** [symphonycms/workspace#16]
In a lengthy [discussion about Symphony breaking on corrupted data](https://github.com/symphonycms/symphony-2/commit/58bc57f2a4153ce0d7ad0e47406ab4a9e6b60746) we asked ourselves : "How can it ever happen that Input fields do not use a `UNIQUE KEY` on the `entry_id` column?"

Here is one way: Start your website with this workspace — __all__ input fields are missing the `UNIQUE` constraint.

I haven't checked any other field types.

**Comment by nitriques** [comment]
@michael-e Can you review (and test if possible) the latest integration branch. Should fix the problem.

**Comment by michael-e** [comment]
Reviewed and tested (performing a fresh install and verifying the results in the database). LGTM.

**Comment by nitriques** [comment]
Merged! Thanks!
