### ISSUE TITLE
Incompatibility with Symphony 2.7.x

### ISSUE THREAD

**Issue by michael-e** [symphonycms/workspace#17]
The default workspace is incompatible with Symphony 2.7.x, because `install.sql` does not honor the new columns (in `tbl_sections` and `tbl_entries`). You will see errors like this:

> Symphony Fatal Database Error: Unknown column 'e.modification_author_id' in 'field list'

**Comment by nitriques** [comment]
This should be fixed with https://github.com/symphonycms/symphony-2/commit/18a166e3d983f6f93f57597b9a0a8fb97d6dc916 which adds a default values for those columns. Insert should still be working fine.

**Comment by michael-e** [comment]
Yep, thanks!
